# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlKarbon < Formula
  desc "Kubectl extension to quickly connect to an existing karbon cluster!"
  homepage "https://github.com/nutanix/kubectl-karbon"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nutanix/kubectl-karbon/releases/download/v0.11.0/kubectl-karbon_v0.11.0_darwin_arm64.tar.gz"
      sha256 "f45ef16bf2989b0499fc32c52520d3f32d82477e56fcd80035e15f1edd5da54b"

      def install
        bin.install "kubectl-karbon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nutanix/kubectl-karbon/releases/download/v0.11.0/kubectl-karbon_v0.11.0_darwin_amd64.tar.gz"
      sha256 "0c1cb7ceef8695e77dbb40f06df10e20ce39d5aaa763b832807a457449d61ae1"

      def install
        bin.install "kubectl-karbon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nutanix/kubectl-karbon/releases/download/v0.11.0/kubectl-karbon_v0.11.0_linux_amd64.tar.gz"
      sha256 "5992aead4e9bd7dab5366288e4cd010d1a8e5b46c0bcccf2b5a2e731a301b71d"

      def install
        bin.install "kubectl-karbon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nutanix/kubectl-karbon/releases/download/v0.11.0/kubectl-karbon_v0.11.0_linux_arm64.tar.gz"
      sha256 "180c30c266df7a671d2058f40fe4bd5125ab34de5dfdf9ee9f3c9236d10b2227"

      def install
        bin.install "kubectl-karbon"
      end
    end
  end

  test do
    system "kubectl-karbon version"
  end
end
