# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlKarbon < Formula
  desc "Kubectl extension to quickly connect to an existing karbon cluster!"
  homepage "https://github.com/nutanix/kubectl-karbon"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nutanix/kubectl-karbon/releases/download/v0.9.0/kubectl-karbon_v0.9.0_darwin_arm64.tar.gz"
      sha256 "18dd0aa4ad9fa94dcd2e0fbde6f904fba6ca7843b797c7c5c907ff6c9ca9b671"

      def install
        bin.install "kubectl-karbon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nutanix/kubectl-karbon/releases/download/v0.9.0/kubectl-karbon_v0.9.0_darwin_amd64.tar.gz"
      sha256 "ba8c52ad6a5a4e8aee7f8a16503afa8c2a91e4947195ab6c09f5f284d0ec34a6"

      def install
        bin.install "kubectl-karbon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nutanix/kubectl-karbon/releases/download/v0.9.0/kubectl-karbon_v0.9.0_linux_amd64.tar.gz"
      sha256 "010e4db1c175d753721e385aab598d2eabcf772ea9e1e90a2644d6081ade8d3a"

      def install
        bin.install "kubectl-karbon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nutanix/kubectl-karbon/releases/download/v0.9.0/kubectl-karbon_v0.9.0_linux_arm64.tar.gz"
      sha256 "172508fd3a50614078e872109a2769583eb93b241d4819a0d6e1ddcbc5b51a3e"

      def install
        bin.install "kubectl-karbon"
      end
    end
  end

  test do
    system "kubectl-karbon version"
  end
end
