# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlKarbon < Formula
  desc "Kubectl extension to quickly connect to an existing karbon cluster!"
  homepage "https://github.com/nutanix/kubectl-karbon"
  version "0.11.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nutanix/kubectl-karbon/releases/download/v0.11.5/kubectl-karbon_v0.11.5_darwin_amd64.tar.gz"
      sha256 "70fff5b93cec6391b057ec187326bbf187561e25757159ee18f0333d6c6c6703"

      def install
        bin.install "kubectl-karbon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nutanix/kubectl-karbon/releases/download/v0.11.5/kubectl-karbon_v0.11.5_darwin_arm64.tar.gz"
      sha256 "3508c7bfe14c58add8ec10463541a3e476bd56639fccf4a502956273f9bf12f2"

      def install
        bin.install "kubectl-karbon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nutanix/kubectl-karbon/releases/download/v0.11.5/kubectl-karbon_v0.11.5_linux_arm64.tar.gz"
      sha256 "09f60cb158d219744a6509c3afff7a9ba57ec9c3d2fcb69539f31bd7b970a361"

      def install
        bin.install "kubectl-karbon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nutanix/kubectl-karbon/releases/download/v0.11.5/kubectl-karbon_v0.11.5_linux_amd64.tar.gz"
      sha256 "5a24ea385a4b9f2fe216d0217625f4b6ab6ae6ff382056a0726aca1b2576ddf8"

      def install
        bin.install "kubectl-karbon"
      end
    end
  end

  test do
    system "kubectl-karbon version"
  end
end
